version: "3.0"

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
    ## note: when running studies for real it is recommended to add the option --output-format='csv.gz' to the run command, 
    ## and add '.gz' to the output file path, to produce the output in compressed form to reduce file size.

  # generate_study_population:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_flow_chart
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_flow_chart.csv

  describe:
    run: r:latest analysis/report.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/descriptive.png

  describe_table1:
    run: r:latest analysis/table_1.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        html: output/descriptive/tables/table*.html
        csv:  output/descriptive/tables/table*.csv
        