version: "3.0"

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  describe:
    run: r:latest analysis/report.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/descriptive.png

  describe_table1:
    run: r:latest analysis/table_1.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        html: output/table*.html
        csv:  output/table*.csv
        